### ISSUE TITLE
Logrotate / other for messages.json?

### ISSUE THREAD

**Issue by Kagee** [vfaergestad/mattermost-logger#1]
How does this behave if logrotate/simmilar renames the messages.json file underfoot of the application (assuming we mount a directory for the file, not the messages.json directly do work around Docker's perciliaries)?

The use is to only have 5-minutes of messages per file to be able to pull it to another host.

**Comment by Kagee** [comment]
Or would it be possible with minute/datefiles (messages.2024-10-07T14-40.json, messages.2024-10-07T14-41.json, messages.2024-10-07T14-42.json, og messages.unix-epoch-per-minute.json etc) instead of a single large messages.json?

**Comment by vfaergestad** [comment]
If I understand the first scenario correctly:

While the bot is running, you would rename the `messages.json` to someting else, lets say `messages.2024-10-07T14-40.json`.

In this case, the bot would just keep writing to the file you renamed, regardless of the name of the file. I believe this is because the bot opens the file only ones and keeps it open, referencing to the file by its file-descriptor, which does not change.

For this to function as wanted, it would either need to close and open the `output_file` once per message, or atleast periodically check if the file was still there before writing. This should be feasable and rather quick to fix.


For the second scenario, implementing logrotation into the bot:

I believe that handling log-rotation is often regarded as a responsibility that should be handled by an external program, like logrotate, instead of being implemented in the application itself. However, just adding the minute as a suffix to the file should be pretty trivial.

I see the options as follows:

- I should improve the log-implementation to support the use of external tools like `logrotate` regardless, by making sure that the bot checks for an existing file before writing.

- Could additionally implement logrotation into the bot, by having a config-option for adding some unix-time as suffix.


@Kagee Do you have any preferences on what fits your usecase the best?

**Comment by Kagee** [comment]
When i comes to logrotate, many daemons supports a Unix signal to trigger closing and re-opening the logfile. Depending on the implementation it is either the process that renames the file to .something on a signal, or the file is renamed externally, then a signal is sendt to instruct the process to closes the old file handle and re-opens the file (using name).

However, are messages.json really *logs*, or is it application output files? And if so, should it be limited by logging standards?

If you choose to support timestamped output files, i would suggest either using epoch, or a configurable format support strftime format. Another property of these files are that assuming a consumer knows the file interval, it does not have to parse the file name to a timestamp to know if a file can be moved, if can be moved based on file last modification time > interval. 

However, depending on how the file open/close is implemented, a possible problem with this solutionis that if no new messages have appeared for a time > interval, the process may still have the last file open, because it has not received any logs that has triggered the closing of the last file and reopening of another. This could be solved with a internal timer on a separate thread that is responsible for closing/opening files.

Another alternative would be supporting (assuming it does not already), writing the messages to STDOUT (and application logs to STDERR for separation). Then messages can be pulled from the Docker logs.

For my personal use, timestamp/epoc-named files that are properly closed would be the optimal solution.

Be aware, that when testing this, mounting a file directly(as in the example) in a Docker container will create problems, since bind mounts are based on inode. Since it is probably the process itself that should create the file if it does not exist, it makes more sense (and fewer headscraches) to mount the folder the output files are written to, not the file itself.

**Comment by vfaergestad** [comment]
>However, are messages.json really logs, or is it application output files? And if so, should it be limited by logging standards?

Good point, it would be smart to differate between the two in this situation.

I will go on and test an implementation of supporting timestamped output-files, and see where it takes me. I will take your notes on possible problems into consideration.

> Be aware, that when testing this, mounting a file directly(as in the example) in a Docker container will create problems, since bind mounts are based on inode. Since it is probably the process itself that should create the file if it does not exist, it makes more sense (and fewer headscraches) to mount the folder the output files are written to, not the file itself.

Also a good point. I actually addressed this in this issue yesterday: https://github.com/vfaergestad/mattermost-logger/issues/2. The updated suggestions in the README of the corresponding pull request should address it.

**Comment by vfaergestad** [comment]
First draft made in https://github.com/vfaergestad/mattermost-logger/commit/9bc643546c48c4a9c103993a94417020b1f0d574

Some issues to be fixed:
- No gracefull shutdown, probably something to do with not all threads being stopped.
- The interval is counted from the start of the program, not from whole minutes or seconds. Like `5m` interval created at 20:53.17 will create a new file 20:58.17.
- Files are created even tho no message is sent.

Gonna work some more on it later.

**Comment by Kagee** [comment]
Alternate way to think of you want to prevent empty files - keep X minutes of messages in ram. When timer triggers or shutdown requested, open/create timestamped message file, write lines, and close.
